/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PaymentContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BNB_RATE"
      | "ETH_RATE"
      | "NATIVE_TOKEN"
      | "USDC_RATE"
      | "USDC_TOKEN"
      | "USDT_RATE"
      | "USDT_TOKEN"
      | "authorizedTokens"
      | "getBalance"
      | "getExchangeRate"
      | "getSupportedTokens"
      | "isOrderProcessed"
      | "owner"
      | "pause"
      | "paused"
      | "payOrderWithNative"
      | "payOrderWithToken"
      | "processedOrders"
      | "recipientWallet"
      | "renounceOwnership"
      | "setRecipientWallet"
      | "setTokenAuthorization"
      | "transferOwnership"
      | "unpause"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyPause"
      | "EmergencyUnpause"
      | "OrderPaid"
      | "OwnershipTransferred"
      | "PaymentFailed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BNB_RATE", values?: undefined): string;
  encodeFunctionData(functionFragment: "ETH_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "NATIVE_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "USDC_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDT_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "USDT_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExchangeRate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOrderProcessed",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payOrderWithNative",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "payOrderWithToken",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processedOrders",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recipientWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRecipientWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenAuthorization",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BNB_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ETH_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "NATIVE_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDT_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDT_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOrderProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payOrderWithNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payOrderWithToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recipientWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecipientWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace EmergencyPauseEvent {
  export type InputTuple = [caller: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [caller: string, timestamp: bigint];
  export interface OutputObject {
    caller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyUnpauseEvent {
  export type InputTuple = [caller: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [caller: string, timestamp: bigint];
  export interface OutputObject {
    caller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderPaidEvent {
  export type InputTuple = [
    orderId: string,
    payer: AddressLike,
    amount: BigNumberish,
    token: AddressLike,
    paymentMethod: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    payer: string,
    amount: bigint,
    token: string,
    paymentMethod: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: string;
    payer: string;
    amount: bigint;
    token: string;
    paymentMethod: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentFailedEvent {
  export type InputTuple = [
    orderId: string,
    payer: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    payer: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: string;
    payer: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentContract extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentContract;
  waitForDeployment(): Promise<this>;

  interface: PaymentContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BNB_RATE: TypedContractMethod<[], [bigint], "view">;

  ETH_RATE: TypedContractMethod<[], [bigint], "view">;

  NATIVE_TOKEN: TypedContractMethod<[], [string], "view">;

  USDC_RATE: TypedContractMethod<[], [bigint], "view">;

  USDC_TOKEN: TypedContractMethod<[], [string], "view">;

  USDT_RATE: TypedContractMethod<[], [bigint], "view">;

  USDT_TOKEN: TypedContractMethod<[], [string], "view">;

  authorizedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getBalance: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getExchangeRate: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getSupportedTokens: TypedContractMethod<[], [string[]], "view">;

  isOrderProcessed: TypedContractMethod<[orderId: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payOrderWithNative: TypedContractMethod<[orderId: string], [void], "payable">;

  payOrderWithToken: TypedContractMethod<
    [orderId: string, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  processedOrders: TypedContractMethod<[arg0: string], [boolean], "view">;

  recipientWallet: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRecipientWallet: TypedContractMethod<
    [_recipientWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenAuthorization: TypedContractMethod<
    [token: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BNB_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ETH_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NATIVE_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExchangeRate"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSupportedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isOrderProcessed"
  ): TypedContractMethod<[orderId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payOrderWithNative"
  ): TypedContractMethod<[orderId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "payOrderWithToken"
  ): TypedContractMethod<
    [orderId: string, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processedOrders"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "recipientWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRecipientWallet"
  ): TypedContractMethod<[_recipientWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenAuthorization"
  ): TypedContractMethod<
    [token: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EmergencyPause"
  ): TypedContractEvent<
    EmergencyPauseEvent.InputTuple,
    EmergencyPauseEvent.OutputTuple,
    EmergencyPauseEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyUnpause"
  ): TypedContractEvent<
    EmergencyUnpauseEvent.InputTuple,
    EmergencyUnpauseEvent.OutputTuple,
    EmergencyUnpauseEvent.OutputObject
  >;
  getEvent(
    key: "OrderPaid"
  ): TypedContractEvent<
    OrderPaidEvent.InputTuple,
    OrderPaidEvent.OutputTuple,
    OrderPaidEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentFailed"
  ): TypedContractEvent<
    PaymentFailedEvent.InputTuple,
    PaymentFailedEvent.OutputTuple,
    PaymentFailedEvent.OutputObject
  >;

  filters: {
    "EmergencyPause(address,uint256)": TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;
    EmergencyPause: TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;

    "EmergencyUnpause(address,uint256)": TypedContractEvent<
      EmergencyUnpauseEvent.InputTuple,
      EmergencyUnpauseEvent.OutputTuple,
      EmergencyUnpauseEvent.OutputObject
    >;
    EmergencyUnpause: TypedContractEvent<
      EmergencyUnpauseEvent.InputTuple,
      EmergencyUnpauseEvent.OutputTuple,
      EmergencyUnpauseEvent.OutputObject
    >;

    "OrderPaid(string,address,uint256,address,string,uint256)": TypedContractEvent<
      OrderPaidEvent.InputTuple,
      OrderPaidEvent.OutputTuple,
      OrderPaidEvent.OutputObject
    >;
    OrderPaid: TypedContractEvent<
      OrderPaidEvent.InputTuple,
      OrderPaidEvent.OutputTuple,
      OrderPaidEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentFailed(string,address,string,uint256)": TypedContractEvent<
      PaymentFailedEvent.InputTuple,
      PaymentFailedEvent.OutputTuple,
      PaymentFailedEvent.OutputObject
    >;
    PaymentFailed: TypedContractEvent<
      PaymentFailedEvent.InputTuple,
      PaymentFailedEvent.OutputTuple,
      PaymentFailedEvent.OutputObject
    >;
  };
}
